### ISSUE TITLE
How to incorporate document title?

### ISSUE THREAD

**Issue by mcelvg** [LIAAD/yake#1]
Can you share the strategy used to leverage document titles for keyword extraction, as in the [demo](http://bit.ly/YakeDemoECIR2018)? I didn't see it mentioned in the [paper](https://repositorio.inesctec.pt/bitstream/123456789/7622/1/P-00N-NF3.pdf)...

**Comment by arianpasquali** [comment]
As @vitordouzi mentioned, there is no special feature for the title. It is concatenated in the beginning of the text. This is an user interface feature only for the demo .
