### ISSUE TITLE
AttributeError: 'numpy.float64' object has no attribute 'upper'

### ISSUE THREAD

**Issue by vgoklani** [LIAAD/yake#10]
Did you make a change to the library?

keywords = set([_[1].upper() for _ in kw_extractor.extract_keywords(text)])

now throws an exception because the tuple looks like:

[('yankees', 0.08596317751626563)]

it used to be flipped.

**Comment by arianpasquali** [comment]
Yes. To keep compatibility with other KE framework we had to make the change.
