### ISSUE TITLE
The dependency on click

### ISSUE THREAD

**Issue by zvezdan** [LIAAD/yake#11]
Can the dependency on click be changed to use lowercase: https://github.com/LIAAD/yake/blob/v0.4.1/setup.py#L13

There was only a single release of Click with uppercase (7.0) and that was a mistake. See: https://github.com/pallets/click/commit/0d95fb0d234d2bfe0a29f673399b72b4b42e1fb2

I just asked for a hotfix release of click that would fix that: https://github.com/pallets/click/issues/1284

In the meantime, if you could change the dependency on the line 13 in setup.py as:
```
'click>=6.0'
```
that would allow users of this package to pick up other versions and hotfixes of click during build. With the current setting of `Click>=6.0`, the build always picks up just `Click-7.0`, which may conflict with another package resolving this to `click-x.y.z` in some build environments.

**Comment by arianpasquali** [comment]
fixed. thanks
