### ISSUE TITLE
Is v0.4.1 available on pypi?

### ISSUE THREAD

**Issue by c-shekhar** [LIAAD/yake#12]

**Comment by c-shekhar** [comment]
I am unable to pip install v0.4.1
`ERROR: Could not find a version that satisfies the requirement yake==0.4.1 (from -r /root/requirements.txt (line 2)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.4, 0.3.0, 0.3.2, 0.3.7)`
Looks like it isn't.

**Comment by arianpasquali** [comment]
Hi @c-shekhar 
Last versions are only available here at github.
