### ISSUE TITLE
extract_keywords_by_url not available

### ISSUE THREAD

**Issue by Joulss** [LIAAD/yake#13]
After building the  docker container, (yake-server), the routes are not the same as the ones provided by the demo. Did I miss something ? Thks.

**Comment by arianpasquali** [comment]
Hi @Joulss 
Unfortunately this method is only available at http://yake.inesctec.pt demo.
Dockers versions is a simpler version of the demo to illustrate how to use it. 

We use the library [newspaper](https://github.com/codelucas/newspaper) to provide that.
Just download the url, clean the boilerplate code using [newspaper](https://github.com/codelucas/newspaper) and run yake on top of it.
