### ISSUE TITLE
Problem with YAKE installation

### ISSUE THREAD

**Issue by drmuskangarg** [LIAAD/yake#14]
I get Error message "'encoding' is an invalid keyword argument for this function" when I try to install YAKE

**Comment by arianpasquali** [comment]
Hi @drmuskangarg 
Can you please show us the full stack trace?

What is your environment?

**Comment by sylwiaoz** [comment]
Hello,
I got the same error message when trying to install Yake. Here's the full trace:

Collecting git+https://github.com/LIAAD/yake
  Cloning https://github.com/LIAAD/yake to /tmp/pip-LJ91Br-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-LJ91Br-build/setup.py", line 8, in <module>
        with open('README.md', encoding='utf-8') as readme_file:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-LJ91Br-build/

I'm on Ubuntu 18.04.

I would appreciate if you could help.
Cheers
Sylwia

**Comment by CVeniamin** [comment]
@sylwiaoz and @drmuskangarg, removing the `encoding` argument from `setup.py` does the trick.

**Comment by sylwiaoz** [comment]
Hi @CVeniamin,

Thank you for your message!

Just to make sure how to go about the installation in that case:

- dowload yake-master.zip
- remove encording argument in setup.py
- run setup.py.

Is that correct?

Cheers
Sylwia
