### ISSUE TITLE
import: no module named yake

### ISSUE THREAD

**Issue by sylwiaoz** [LIAAD/yake#18]
Hello,

I  just installed yake but then when I want to used it, I am getting an error message following import yake command:

  File "<stdin>", line 1, in <module>
  File "/home/sylwia/.local/lib/python2.7/site-packages/yake/__init__.py", line 9, in <module>
    from yake.yake import KeywordExtractor
ImportError: No module named yake

I would appreciate your help with that.
Cheers
Sylwia

**Comment by sandeep-manikonda** [comment]
Hi Sylwia,
This pkg works for python 3.x as mentioned in the Readme and the setup file. It looks like you are using python 2.7. Updating python should hopefully solve the issue.
The dev team should have made it compatible to prev python versions as well for this pretty simple to use pkg.
Note: Iam not part of the dev team, just another user.
