### ISSUE TITLE
is multi language possible?

### ISSUE THREAD

**Issue by maozida880** [LIAAD/yake#19]
I had installed the software after three dependency packages  installed successfully
but it is now used in English key words extraction. 
Would Chinese work as well ?

**Comment by arianpasquali** [comment]
You need to specify "lan" parameter. By default it is english.

In theory Chinese should work passing the 'zh' as language argument.
`yake.KeywordExtractor(lan="zh")`

We can not guarantee it works well because it wasn't tested with Chinese datasets.

Let me know how it goes.
