### ISSUE TITLE
problem installing yake on linux 

### ISSUE THREAD

**Issue by gstattcm** [LIAAD/yake#20]
hello, i've tried to install yake using pip over linux and i get the following error:

> pip install yake
Collecting yake
Requirement already satisfied: networkx in ./anaconda3/lib/python3.7/site-packages (from yake) (2.3)
Requirement already satisfied: Click>=6.0 in ./anaconda3/lib/python3.7/site-packages (from yake) (7.0)
Collecting jellyfish (from yake)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from yake) (1.3.1)
Collecting unidecode>=0.4.19 (from yake)
  Using cached https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: nltk>=3.1 in ./anaconda3/lib/python3.7/site-packages (from yake) (3.4.4)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from yake) (1.16.4)
Requirement already satisfied: fire in ./anaconda3/lib/python3.7/site-packages (from yake) (0.2.1)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.7/site-packages (from yake) (0.25.0)
Collecting segtok (from yake)
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/lib/python3.7/site-packages (from networkx->yake) (4.4.0)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from nltk>=3.1->yake) (1.12.0)
Requirement already satisfied: termcolor in ./anaconda3/lib/python3.7/site-packages (from fire->yake) (1.1.0)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.7/site-packages (from pandas->yake) (2019.1)
Requirement already satisfied: python-dateutil>=2.6.1 in ./anaconda3/lib/python3.7/site-packages (from pandas->yake) (2.8.0)
Collecting regex (from segtok->yake)
  Using cached https://files.pythonhosted.org/packages/6f/a6/99eeb5904ab763db87af4bd71d9b1dfdd9792681240657a4c0a599c10a81/regex-2019.08.19.tar.gz
Building wheels for collected packages: regex
  Building wheel for regex (setup.py) ... error
  ERROR: Complete output from command /home/ec2-user/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-phwl6li7/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kz_s22lg --python-tag cp37:
  ERROR: BASE_DIR is /tmp/pip-install-phwl6li7/regex
  /home/ec2-user/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2019.08.19' to '2019.8.19'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/regex
  copying regex_3/regex/__init__.py -> build/lib.linux-x86_64-3.7/regex
  copying regex_3/regex/regex.py -> build/lib.linux-x86_64-3.7/regex
  copying regex_3/regex/_regex_core.py -> build/lib.linux-x86_64-3.7/regex
  creating build/lib.linux-x86_64-3.7/regex/test
  copying regex_3/regex/test/__init__.py -> build/lib.linux-x86_64-3.7/regex/test
  copying regex_3/regex/test/test_regex.py -> build/lib.linux-x86_64-3.7/regex/test
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/regex_3
  gcc -pthread -B /home/ec2-user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/include/python3.7m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.7/regex_3/_regex.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex

> Failed to build regex
Installing collected packages: jellyfish, unidecode, regex, segtok, yake
  Running setup.py install for regex ... error
    ERROR: Complete output from command /home/ec2-user/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-phwl6li7/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x34h1jjm/install-record.txt --single-version-externally-managed --compile:
    ERROR: BASE_DIR is /tmp/pip-install-phwl6li7/regex
    /home/ec2-user/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2019.08.19' to '2019.8.19'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/regex
    copying regex_3/regex/__init__.py -> build/lib.linux-x86_64-3.7/regex
    copying regex_3/regex/regex.py -> build/lib.linux-x86_64-3.7/regex
    copying regex_3/regex/_regex_core.py -> build/lib.linux-x86_64-3.7/regex
    creating build/lib.linux-x86_64-3.7/regex/test
    copying regex_3/regex/test/__init__.py -> build/lib.linux-x86_64-3.7/regex/test
    copying regex_3/regex/test/test_regex.py -> build/lib.linux-x86_64-3.7/regex/test
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/regex_3
    gcc -pthread -B /home/ec2-user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/include/python3.7m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.7/regex_3/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/ec2-user/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-phwl6li7/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x34h1jjm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-phwl6li7/regex/
(base) [ec2-user@ip-172-31-21-203 ~]$ pip install git+https://github.com/LIAAD/yake
Collecting git+https://github.com/LIAAD/yake
  Cloning https://github.com/LIAAD/yake to /tmp/pip-req-build-dejjnuzx
  Running command git clone -q https://github.com/LIAAD/yake /tmp/pip-req-build-dejjnuzx
Collecting tabulate (from yake==0.4.2)
  Downloading https://files.pythonhosted.org/packages/66/d4/977fdd5186b7cdbb7c43a7aac7c5e4e0337a84cb802e154616f3cfc84563/tabulate-0.8.5.tar.gz (45kB)
     |████████████████████████████████| 51kB 24.4MB/s
Requirement already satisfied: click>=6.0 in ./anaconda3/lib/python3.7/site-packages (from yake==0.4.2) (7.0)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from yake==0.4.2) (1.16.4)
Collecting segtok (from yake==0.4.2)
Requirement already satisfied: networkx in ./anaconda3/lib/python3.7/site-packages (from yake==0.4.2) (2.3)
Requirement already satisfied: jellyfish in ./anaconda3/lib/python3.7/site-packages (from yake==0.4.2) (0.7.2)
Collecting regex (from segtok->yake==0.4.2)
  Using cached https://files.pythonhosted.org/packages/6f/a6/99eeb5904ab763db87af4bd71d9b1dfdd9792681240657a4c0a599c10a81/regex-2019.08.19.tar.gz
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/lib/python3.7/site-packages (from networkx->yake==0.4.2) (4.4.0)
Building wheels for collected packages: yake, tabulate, regex
  Building wheel for yake (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-gqhzo3j2/wheels/be/35/27/e4ebd54b78c1806ed8b0271ce247fcd91e2bedde35889fbc9b
  Building wheel for tabulate (setup.py) ... done
  Stored in directory: /home/ec2-user/.cache/pip/wheels/e1/41/5e/e201f95d90fc84f93aa629b6638adacda680fe63aac47174ab
  Building wheel for regex (setup.py) ... error
  ERROR: Complete output from command /home/ec2-user/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-pqiwlp28/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3pkjcr_k --python-tag cp37:
  ERROR: BASE_DIR is /tmp/pip-install-pqiwlp28/regex
  /home/ec2-user/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2019.08.19' to '2019.8.19'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/regex
  copying regex_3/regex/__init__.py -> build/lib.linux-x86_64-3.7/regex
  copying regex_3/regex/regex.py -> build/lib.linux-x86_64-3.7/regex
  copying regex_3/regex/_regex_core.py -> build/lib.linux-x86_64-3.7/regex
  creating build/lib.linux-x86_64-3.7/regex/test
  copying regex_3/regex/test/__init__.py -> build/lib.linux-x86_64-3.7/regex/test
  copying regex_3/regex/test/test_regex.py -> build/lib.linux-x86_64-3.7/regex/test
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/regex_3
  gcc -pthread -B /home/ec2-user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/include/python3.7m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.7/regex_3/_regex.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex
Successfully built yake tabulate
Failed to build regex
Installing collected packages: tabulate, regex, segtok, yake
  Running setup.py install for regex ... error
    ERROR: Complete output from command /home/ec2-user/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-pqiwlp28/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-aot88mu6/install-record.txt --single-version-externally-managed --compile:
    ERROR: BASE_DIR is /tmp/pip-install-pqiwlp28/regex
    /home/ec2-user/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2019.08.19' to '2019.8.19'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/regex
    copying regex_3/regex/__init__.py -> build/lib.linux-x86_64-3.7/regex
    copying regex_3/regex/regex.py -> build/lib.linux-x86_64-3.7/regex
    copying regex_3/regex/_regex_core.py -> build/lib.linux-x86_64-3.7/regex
    creating build/lib.linux-x86_64-3.7/regex/test
    copying regex_3/regex/test/__init__.py -> build/lib.linux-x86_64-3.7/regex/test
    copying regex_3/regex/test/test_regex.py -> build/lib.linux-x86_64-3.7/regex/test
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/regex_3
    gcc -pthread -B /home/ec2-user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/include/python3.7m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.7/regex_3/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------

> ERROR: Command "/home/ec2-user/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-pqiwlp28/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-aot88mu6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-pqiwlp28/regex/

can you help in some way?

**Comment by arianpasquali** [comment]
Please use 
`pip install git+https://github.com/LIAAD/yake`

The pip repository is currently not longer supported.
