### ISSUE TITLE
Taking too long to train for 

### ISSUE THREAD

**Issue by rudraina** [LIAAD/yake#22]
For numOfKeywords >1K(~5K/10K) speed of training drops drastically. Is there any way to make learning more efficient/faster? 
I am passing the whole corpus of text as single entity(tried as a string and as from a file.txt)

**Comment by arianpasquali** [comment]
Hi @rudraina 
It wasn't designed with that in mind. There might be a mistake here. YAKE is not a supervised method, so there is no training here. There is no reason to pass a whole corpus to the method. It expects single documents as input.
