### ISSUE TITLE
Error with upgrade command

### ISSUE THREAD

**Issue by engrsfi** [LIAAD/yake#23]
I get an error when I run the YAKE upgrade command.

Command:
`pip install git+https://github.com/LIAAD/yake –upgrade`

Error:
`ERROR: Invalid requirement: '\u2013upgrade'`

Any ideas, why?

**Comment by arianpasquali** [comment]
Hi @engrsfi 
I believe the correct syntax should be --upgrade instead of -upgrade.
It was a mistake in the documentation. Fixed
