### ISSUE TITLE
Allow custom stopwords

### ISSUE THREAD

**Issue by erip** [LIAAD/yake#24]
Thanks for an awesome package! I'd love to be able to provide a custom stopwords list, but it doesn't seem like this is currently possible since the stopwords list is loaded from a file. 

One option would be to add an optional stopwords list with a default `None` to the `KeywordExtractor` constructor and load the file in the default case. If this seems reasonable, I'd be happy to send a PR along.

**Comment by arianpasquali** [comment]
Hi @erip .
I like the idea.
Fell free to send the PR :)

best

**Comment by erip** [comment]
Done - thanks, @arianpasquali!

**Comment by arianpasquali** [comment]
I see what you mean now. This is simpler than I imagined. I thought you wanted to add custom stopwords in addition to a pre-defined stopword set and not replace them. I don't see a problem with that.

In this case, by default the algorithm will choose the stopwords for the specified language. In case you specify your own stopwords set the algorithm will ignore the language stopwords and rely on your only.

**Comment by arianpasquali** [comment]
Thank you @erip.

With custom stopwords support you can handle the stopword set yourself and eventually add domain specific stopwords.
