### ISSUE TITLE
Does yake surpport Chinese words ？

### ISSUE THREAD

**Issue by lemon234071** [LIAAD/yake#40]

**Comment by arianpasquali** [comment]
It basically just need stopwords list for western languages. 

I can't promise optimal performance for Chinese, but it
supports Chinese stopwords as you can see here https://github.com/LIAAD/yake/blob/master/yake/StopwordsList/stopwords_zh.txt

So all you need to do is set zh as lang parameter.

You can edit the stopword list as you wish.

**Comment by lemon234071** [comment]
Thank you very much !

**Comment by lemon234071** [comment]
Thanks for an awesome package again!
But i try bellow codes , it seems that yake does not work.... 
>>> import yake
>>> kw_extractor = yake.KeywordExtractor(lan="zh", stopwords=stopkey)
>>> text = "至少 你 有 锁骨 了 ！练 天鹅 臂 , 什么 是 天鹅 臂 。 。 。, b 站 腾讯 视频 都 有 一 个 练 手臂 的 视频"
>>> kw_extractor.extract_keywords(text)
out: []

I would appreciate if you could help.
best

**Comment by arianpasquali** [comment]
what did you specified in "stopkey"?

**Comment by lemon234071** [comment]
> what did you specified in "stopkey"?
> you don't need to specified stopwords, only if you want to overwrite the default stopwords defined for `zh`.

It's just a normal stop list. 
Even if I don't specify this parameter, it still can't extract keywords normally:

    yake.KeywordExtractor(lan="zh") 

Is it because the text is too short?

**Comment by arianpasquali** [comment]
I would say that it is because the text is too short for Chineese. I ve just tried with longer thext and it works.

**Comment by hjing100** [comment]
import yake

text = "重庆晚报6月11日报道  昨日，市政府公众信息网发布消息称，经2010年5月13日市政府第70次常务会议通过，给予文强、陈洪刚二人行政开除处分。今年4月14日，市第五中级人民法院以受贿罪，包庇、纵容黑社会性质组织罪，巨额财产来源不明罪，强奸罪数罪并罚判处文强死刑，剥夺政治权利终身，并处没收个人全部财产。5月21日，市高级人民法院对文强案二审宣判，依法驳回文强上诉，维持一审的死刑判决。2月25日，市公安局交警总队原总队长陈洪刚受贿案在市第五中级人民法院一审宣判。陈洪刚因犯受贿，包庇、纵容黑社会性质组织，巨额财产来源不明，伪造居民身份证罪，数罪并罚，被判处有期徒刑20年，没收个人财产40万元人民币，追缴赃款326万余元及不明来源财产584万余元。"

kw_extractor = yake.KeywordExtractor(lan="zh",top=5)
keywords = kw_extractor.extract_keywords(text)

for kw in keywords:
	print(kw)

result:
('日报道 昨日，市政府公众信息网发布消息称，经', 0.004038337355251095)
('重庆晚报', 0.04491197687864554)
('日市政府第', 0.04491197687864554)
('次常务会议通过，给予文强、陈洪刚二人行政开除处分。今年', 0.04491197687864554)
('日，市第五中级人民法院以受贿罪，包庇、纵容黑社会性质组织罪，巨额财产来源不明罪，强奸罪数罪并罚判处文强死刑，剥夺政治权利终身，并处没收个人全部财产。', 0.04491197687864554)

As you say, the performance is not good.

**Comment by Sanster** [comment]
You should cut words first

```python
kw_extractor = yake.KeywordExtractor(lan="zh", n=1, top=5)
text = " ".join(list(jieba.cut_for_search(text)))
kw_extractor.extract_keywords(text)
```

**Comment by Junesui** [comment]
> _No description provided._

最后找到替代方案了吗
