### ISSUE TITLE
YAKE at PyPI

### ISSUE THREAD

**Issue by PrimozGodec** [LIAAD/yake#42]
Dear authors, thank you for the great method and its implementation as a Python package. 

We want to use Yake as a part of a package which will also be published at PyPI. We have an issue with Yake not being published at PyPI, since it cannot be used as the dependency of another package (when the package is installed with pip it cannot have the dependency from GitHub). I know you decided to deprecate the PyPI version of this package but I would ask if you can rethink this decision. Publishing the package at PyPI takes just two additional commands to be executed on the release.

I do not know what exactly led to this decision but if there is any technical reason I would be happy to help.

**Comment by arianpasquali** [comment]
hi @PrimozGodec .
I ll provide that again. It is indeed important to have it published there again.

**Comment by PrimozGodec** [comment]
@arianpasquali thank you for fast response and willingness to provide the package at PyPI again.

**Comment by arianpasquali** [comment]
Hi @PrimozGodec 
It is back online at PyPI at https://pypi.org/project/yake/

So everyone can use simply

```
pip install yake
```

cheers

**Comment by PrimozGodec** [comment]
Thank a lot. :)
