### ISSUE TITLE
Available languages list

### ISSUE THREAD

**Issue by BugKiller-tech** [LIAAD/yake#51]
Where can I find a list of languages available in this library ?

```
yake.KeywordExtractor(lan=.....)
```
in parameter lan, I can pass "en" for English.
What other languages are available ? any documentation for that ?

**Comment by arianpasquali** [comment]
Hi @BugKiller-tech 
You need specify the 2 chars iso code for the language.

You can check the supported languages here
https://github.com/LIAAD/yake/tree/master/yake/StopwordsList

**Comment by BugKiller-tech** [comment]
yes, I've just checked the code and I realized it.
So here the lan is only used to pick stop words ?

**Comment by arianpasquali** [comment]
That is it @BugKiller-tech. Just for the stopwords.
