### ISSUE TITLE
how does the demo, finds similar words?

### ISSUE THREAD

**Issue by breathingcyborg** [LIAAD/yake#55]
In the offifical demo, hovering over the keyword highlights keywords that are similar to that keyword. How does that work?

**Comment by arianpasquali** [comment]
This is just a logic for the demo. It looks for other ngrams that include the ngram that you are hovering. For instance if you hover over "Obama" it will look for other ngrams that contains the token `Obama`, in this case it would highlight ngrams like `Barack Obama`,  `President Obama`, `Miss Obama`, etc.
