### ISSUE TITLE
Configurable term length and terms containing numbers

### ISSUE THREAD

**Issue by tdxius** [LIAAD/yake#68]
In general, I'm very happy with the keyword extractions I get from this library, but I faced a few challenges:

- it only extracts terms longer than 2 characters (terms like EU, US, AI,... which are relevant for my use case are not extracted) 
- terms containing a number are not extracted (B2B, B2C, P2P,...)

Would it be possible to make it a CLI option? Something like the example below?

```bash
Usage: yake [OPTIONS]

Options:
	-mt, --min-term-length INTEGER          Minimum length of a term that is extracted
        -tn, --term-contains-numbers               Extracted terms can contain numbers

```

**Comment by rncampos** [comment]
You welcome. Sure. We will include. It will also be a good idea to have that as a parameter when calling the function (beyond having it also on the cli). Best
