### ISSUE TITLE
ModuleNotFoundError: No module named 'regex._regex_core'; 'regex' is not a package

### ISSUE THREAD

**Issue by vgoklani** [LIAAD/yake#8]
Problems installing on my macbook pro: running python 3.6

    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-3-7cd11dc808be> in <module>
    ----> 1 import yake

    ~/anaconda3/lib/python3.6/site-packages/yake/__init__.py in <module>
          7 __version__ = '0.4.0'
          8 
    ----> 9 from yake.yake import KeywordExtractor

    ~/anaconda3/lib/python3.6/site-packages/yake/yake.py in <module>
          8 from .Levenshtein import Levenshtein
          9 
    ---> 10 from .datarepresentation import DataCore
         11 
         12 class KeywordExtractor(object):

    ~/anaconda3/lib/python3.6/site-packages/yake/datarepresentation.py in <module>
    ----> 1 from segtok.segmenter import split_multi
          2 from segtok.tokenizer import web_tokenizer, split_contractions
          3 
          4 import networkx as nx
          5 import numpy as np

    ~/anaconda3/lib/python3.6/site-packages/segtok/segmenter.py in <module>
         28 from __future__ import absolute_import, unicode_literals
         29 import codecs
    ---> 30 from regex import compile, DOTALL, UNICODE, VERBOSE
         31 
         32 

    ~/anaconda3/lib/python3.6/site-packages/regex.py in <module>
        398 # Internals.
        399 
    --> 400 import regex._regex_core as _regex_core
        401 import regex._regex as _regex
        402 from threading import RLock as _RLock

    ModuleNotFoundError: No module named 'regex._regex_core'; 'regex' is not a package

**Comment by vitordouzi** [comment]
This error occurs in the segtok package. Try to update the segtok (I met its author, and he uses mac):

`pip install --upgrade segtok` or `pip3 install --upgrade segtok`

**Comment by jctommasi** [comment]
try 

`pip install regex`

**Comment by jinnchoi** [comment]
I solved it like this.
pip uninstall regex
pip install regex      # i reinstalled regex
# Then I reinstalled nltk again
pip uninstall nltk
pip install nltk

it works well
